### PR TITLE
show app info in sideload view

### PR DESCRIPTION
**Pull request by wilds**
image

### CODE REVIEW

**Comment by barnabwhy** [comment]
I noticed in [wilds/vr-binaries](https://github.com/wilds/vr-binaries) that the manifests aren't easily navigable and the extractor isn't open source. Could this be changed?

**Comment by wilds** [comment]
extractor sources is now available at https://github.com/wilds/apk-manifest-extractor

Filenames are hashed to prevent the exposure of potential cracked applications' filenames. While this makes the manifest less easily navigable, it also makes it challenging to associate the manifest with the file if the file name is unknown.

**Comment by barnabwhy** [comment]
That does make sense, are you manually adding manifests?

**Comment by wilds** [comment]
Yes, for now I generate the manifests with the extractor and manually push them to the repository. I planned to write a script that automatically adds them from a source constantly synchronized with rclone, but due to a hardware problem (RAM failure), I am currently unable to proceed with manifest extraction.

**Comment by barnabwhy** [comment]
Could it possibly be changed to use `https://pico.doesnt-like.me/fileinfo/<filename>` and `https://pico.doesnt-like.me/assets/<packagename>/app.png`?

**Comment by wilds** [comment]
done

**Comment by barnabwhy** [comment]
I wouldn't recommend pinging the store API directly. I do have `GET https://pico.doesnt-like.me/info/<packagename>` (e.g. https://pico.doesnt-like.me/info/VirtualDesktop.Android) set up to send the same data though

**Comment by barnabwhy** [comment]
btw idk if you saw but the api host is now https://api.picozen.app/ and app icons are also now icon.png rather than app.png

**Comment by barnabwhy** [comment]
so this should format work for info https://api.picozen.app/info/VirtualDesktop.Android and this for icons https://api.picozen.app/assets/VirtualDesktop.Android/icon.png

**Comment by barnabwhy** [comment]
Closing this PR as it somewhat contradicts the lack of support for piracy. Ideally if a solution can be made which avoids relying on the specific files and just parses the file names. This feature also isn't really needed for now, file names can store adequate information about the files being downloaded.

**Pull request closed without merging**
